# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 10:32
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cantons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.IntegerField()),
                ('nm_canton', models.CharField(max_length=27)),
                ('prefecture', models.CharField(max_length=12)),
                ('region', models.CharField(max_length=8)),
                ('nbre_cant', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
    ]
